# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - seto-coffee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        env:
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
          COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }}
          COSMOS_DATABASE_ID: ${{ secrets.COSMOS_DATABASE_ID }}
        run: |
          npm install
          npm run build
          npm run postbuild
          rm -rf src .next/cache

      - name: Zip artifact for deployment
        run: |
          cd .next/standalone
          zip -r ../../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
        
      - name: Set environment variables
        run: |
          echo "Setting up environment variables..."
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          echo "SETO_COFFEE_RUN_FROM_PACKAGE=1_${TIMESTAMP}" >> .env.production
          echo "NODE_ENV=production" >> .env.production
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.production
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env.production
          echo "COSMOS_KEY=${{ secrets.COSMOS_KEY }}" >> .env.production
          echo "COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }}" >> .env.production
          echo "COSMOS_DATABASE_ID=${{ secrets.COSMOS_DATABASE_ID }}" >> .env.production
          echo "NEXTAUTH_SECRET_KEY=${{ secrets.NEXTAUTH_SECRET_KEY }}" >> .env.production
          echo "PAYPAY_API_KEY=${{ secrets.PAYPAY_API_KEY }}" >> .env.production
          echo "PAYPAY_API_SECRET=${{ secrets.PAYPAY_API_SECRET }}" >> .env.production
          echo "PAYPAY_MERCHANT_ID=${{ secrets.PAYPAY_MERCHANT_ID }}" >> .env.production

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7CE7CA8065924B638A7BDAF18C6AE8CA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6698D59728384E4B9EF49CEB54A5A436 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_688EFC0401584FE38746C36455388826 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'seto-coffee'
          slot-name: 'Production'
          package: .
          